### ISSUE TITLE
Web Player Level 4 attack glitch/movement

### ISSUE THREAD

**Issue by Dersinex** [Tactibru/Game#116] opened 2013-10-23 06:06 UTC
By using the same attack glitch on level 4, the attacking unit will be left on a random block above, below, or behind the attacked unit. Typically the attacking unit will end up on whatever block the targeted unit was when it was clicked on.

![image](https://f.cloud.github.com/assets/5694936/1387830/a9502d92-3ba8-11e3-8bdb-fa86f16d35fd.png)

![image](https://f.cloud.github.com/assets/5694936/1387842/0123b11a-3ba9-11e3-8a35-7e4161e2c88e.png)

![image](https://f.cloud.github.com/assets/5694936/1387829/9158e846-3ba8-11e3-90d2-b9dff0fea928.png)

**Comment by Minalien** [comment] 2013-10-23 16:33
Duplicate of #115

**Closed as completed** 2013-10-23 16:33 UTC
Labels: bug, duplicate, gameplay
